config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               registrations: 'users/registrations'
             },
             path: '/'
  mount ActionCable.server => '/cable'
  resources :calculators

  root 'calculators#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculator.rb
class Calculator < ApplicationRecord
    #refers to each calculation computed in the app, I unfortunately named it calculator instead of calculation
    belongs_to :user, :optional => true

    after_create_commit {
        CalculationBroadcastJob.perform_later(self)
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :calculators, dependent: :destroy

def username
  return email.split('@')[0]
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  before_action :set_calculator, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /calculators
  # GET /calculators.json
  def index
    @calculations = Calculator.last(10).reverse #set history bound to 10
    @calculation = Calculator.new
  end

  # GET /calculators/1
  # GET /calculators/1.json
  def show
    @calculator = Calculators.find(params)
  end

  # GET /calculators/new
  def new
    @calculator = Calculator.new
  end

  # GET /calculators/1/edit
  def edit
  end

  # POST /calculators
  # POST /calculators.json
  def create
    @calculator = current_user.calculators.new(calculator_params)

    respond_to do |format|
      if @calculator.save
        format.html { redirect_to calculators_path }
        format.json { render :show, status: :created, location: @calculator }
        format.js
      else
        format.html { render :new }
        format.json { render json: @calculator.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculator
      @calculator = Calculator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calculator_params
      params.permit(:content)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:FirstName, :LastName, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:FirstName, :LastName, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculators_helper.rb
module CalculatorsHelper
end

app/views/calculators/_calculation.html.erb
<table>
    <thead>
        <tr>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><%= calculation.user.username %> calculated :</td>
        </tr>

        <tr>
            <td><%= calculation.content %></td>
        </tr>
        
    </tbody>

</table>

app/views/calculators/_calculator.html.erb
<div id = "result">
    <form name="form" form action="/calculators" method="post"  >
        <input class="textview" name="content">
        <input type="submit" value="Submit This Calculation">
    </form>
</div>

<div id = "keyboard">
    <table>
        <tr>
                <td><input type="button" value="C" onclick="clean()"></td>
                <td><input type="button" value="<" onclick="back()"></td>
                <td><input type="button" value="/" onclick="insert('/')"></td>
                <td><input type="button" value="X" onclick="insert('*')"></td>
            </tr>
            <tr>
                <td><input type="button" class = "number" id="7" value="7" onclick="insert(7)"></td>
                <td><input type="button" class = "number" id="8" value="8" onclick="insert(8)"></td>
                <td><input type="button" class = "number" id="9" value="9" onclick="insert(9)"></td>
                <td><input type="button" value="-" onclick="insert('-')"></td>
            </tr>
            <tr>
                <td><input  type="button" class = "number" id="4" value="4" onclick="insert(4)"></td>
                <td><input  type="button" class = "number" id="5" value="5" onclick="insert(5)"></td>
                <td><input  type="button" class = "number" id="6" value="6" onclick="insert(6)"></td>
                <td><input  type="button" value="+" onclick="insert('+')"></td>
            </tr>
            <tr>
                <td><input  type="button" class = "number" id="1" value="1" onclick="insert(1)"></td>
                <td><input  type="button" class = "number" id="2" value="2" onclick="insert(2)"></td>
                <td><input  type="button" class = "number" id="3" value="3" onclick="insert(3)"></td>
                <td><input  type="button" value="=" onclick="equal()"></td>
            </tr>
            <tr>
                <td><input  type="button" value="0" onclick="insert(0)"></td>
                <td><input  type="button" value="." onclick="insert('.')"></td>
            </tr>
    </table>
</div>   

app/views/calculators/_form.html.erb
<%= form_for(calculator) do |f| %>
  <% if calculator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calculator.errors.count, "error") %> prohibited this calculator from being saved:</h2>

      <ul>
      <% calculator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calculators/edit.html.erb
<h1>Editing Calculator</h1>

<%= render 'form', calculator: @calculator %>

<%= link_to 'Show', @calculator %> |
<%= link_to 'Back', calculators_path %>

app/views/calculators/index.html.erb
<!DOCTYPE html>
<html lang = "en">
<html>
    <head>
    <%= csrf_meta_tags%>
    <meta name = "viewport" content="width=device-width, initial-scale=1">
    <title>A simple calculator</title>
    </head>

    <body>
        <div id= "container" >
            <div id = "calculator">
                <%= render 'calculators/calculator' %>
            </div>
            <div id = 'calculations'>
                <div id ='title'>
                    <h2>Calculation History</h2>
                </div>
                <% @calculations.each do |calculation| %>
                    <%= render 'calculators/calculation', calculation: calculation %>
                <% end %>
            </div> 
        </div>
    </body>
</html>

app/views/calculators/new.html.erb
<h1>New Calculator</h1>

<%= render 'form', calculator: @calculator %>

<%= link_to 'Back', calculators_path %>

app/views/calculators/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_calculator_path(@calculator) %> |
<%= link_to 'Back', calculators_path %>

app/views/layouts/_navbar.html.erb
<div id ="navbar">
    <% if current_user %>
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'navbar-brand' %>
    <% else %>
        <%= link_to 'Register', new_user_registration_path, class: 'navbar-brand' %>
        <%= link_to 'Login', new_user_session_path, class: 'navbar-brand' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalculatorApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>